language: python
python: "3.4"

addons:
  postgresql: '9.4'

services:
  - memcached
  - redis-server

compiler: gcc

cache:
  directories:
    - node_modules
    - $HOME/.cache/pip/
    - $HOME/virtualenv/python3.4.2

env:
  global:
    - DJANGO_SETTINGS_MODULE="recipi.conf.travis"
    - RECIPI_TEST_DB_NAME=recipi_test
    - RECIPI_TEST_DB_USER=travis

before_install:
  # Reference custom repos
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

  # add proper c++- compiler for node-sass
  - sudo apt-get install gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  - sudo g++ --version
  - npm config set python /usr/bin/python2.7

before_script:
  - psql -c 'create database recipi_test;' -U postgres

script:
  - psql --version
  - mv resources/nltk_data /home/travis/nltk_data
  - make develop
  - make test

after_success:
  - pip install "coveralls==0.4.1" coverage
  - coverage report
  - coveralls
